### ISSUE TITLE
LuLu pkg is broken, as the installer is now completely different

### ISSUE THREAD

**Issue by grahampugh** [autopkg/apettinen-recipes#14]
I had a quick look, but the whole installer is now embedded in a `.app`, so it's going to be tricky to unpick.

**Comment by apettinen** [comment]
Yep, I've deliberately been waiting for the version 1.0 since in the previous versions the installer has been... well, more or less broken re: distributing in managed environments.
But now it's about time to take another look at it and talk (again) to the author about making it usable in managed environments. 

Thanks for reporting, I'll try to find time to work on this in the next few days.

**Comment by Daz-wallace** [comment]
Bit of a cheeky bump, but is there any news on this? I'm guessing since it's 2018, maybe not 😉

**Comment by Daz-wallace** [comment]
Looks like this issue and #31 are related. Also looks like the installer has changed a lot and as long as you have the right System Extension (and maybe Content filter) profiles in place, it's just a drag and drop install.

I'll work on a PR on this basis for you to review

**Comment by Daz-wallace** [comment]
Looking at the current recipe, theres a fair bit of extra bits that I'll remove for now, but again let me know when I submit the PR for review if anything needs to be added back in

**Comment by apettinen** [comment]
Fixed by https://github.com/autopkg/apettinen-recipes/commit/636cc26086c54048474c2493228ce0b1a7bf02c0

**Comment by apettinen** [comment]
> Bit of a cheeky bump, but is there any news on this? I'm guessing since it's 2018, maybe not 😉

Haha, I kinda kept on pushing this forward for no particular reason, except being 100% General Laziness.
