### ISSUE TITLE
URLDownloader: Error: Curl failure: LibreSSL SSL_read

### ISSUE THREAD

**Issue by maxm-ray** [autopkg/apettinen-recipes#4]
There is something wrong with the MSTeams.download recipe. When i try to `autopkg run -v MSTeams.download` i get the following error:

`The following recipes failed:
    MSTeams.download
        Error in com.github.apettinen.download.MSTeams: Processor: URLDownloader: Error: Curl failure: LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 54 (exit code 56)`

**Comment by apettinen** [comment]
Hi!
I need to take a look! Thanks for reporting!

**Comment by apettinen** [comment]
Hi,

It seems that this issue is not related to the recipe per se, but is an issue with the network. The download recipe works fine for some, but fails for others (me included, on 10.13.4beta at least).

The system curl in macOS uses HTTP/2 if possible by the server-side and it seems that the download will fail (for currently unknown reason) if HTTP/2 is used. If one passes the `--no-alpn` flag to curl, disabling HTTP/2 support, the download works fine. At least with curl 7.54.0.

Could you provide a bit more details on your setup, in order to track this down (OS and curl versions are enough).

**Comment by maxm-ray** [comment]
Hi,

i am using macOS 10.13.3 with curl 7.54.0.

Thanks for supporting.

**Comment by apettinen** [comment]
No problem.

It seems to work now for me too. I'm closing this issue, as it's not really related to the recipe itself, but the underlying mechanisms. 

But thank you once again for reporting! I will keep an eye on if this reappears.
