### ISSUE TITLE
SSL Error with MSTeams.download.recipe

### ISSUE THREAD

**Issue by SeanHansell** [autopkg/apettinen-recipes#5]
Error in com.github.apettinen.download.MSTeams: Processor: URLDownloader: Error: Curl failure: LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 54 (exit code 56)

```
MSTeamsURLProvider
{'Input': {}}
MSTeamsURLProvider: MSTeams URL found: https://statics.teams.microsoft.com/production-osx/1.1.00.5851/Teams_osx.dmg
{'Output': {'url': 'https://statics.teams.microsoft.com/production-osx/1.1.00.5851/Teams_osx.dmg'}}
URLDownloader
{'Input': {'url': 'https://statics.teams.microsoft.com/production-osx/1.1.00.5851/Teams_osx.dmg'}}
URLDownloader: No value supplied for CHECK_FILESIZE_ONLY, setting default value of: False
URLDownloader: No value supplied for CURL_PATH, setting default value of: /usr/bin/curl
Curl failure: LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 54 (exit code 56)
Failed.
```
macOS High Sierra 10.13.3
AutoPkg 1.0.4

**Comment by apettinen** [comment]
Hi,

Thanks for reporting! The same problem was reported a few weeks ago ( see [Issue 4](https://github.com/autopkg/apettinen-recipes/issues/4)). The problem is not in the recipe itself, but it's tied to the underlying mechanisms, more specifically curl and http2 (ALPN), and is most probably caused by server side dropping the connection. Last time the issue resolved itself after a while.

Some background:
Basically curl is exiting with the exit code 56, which based on the header files is `CURLE_RECV_ERROR,              /* 56 - failure in receiving network data */`
This then causes the SSL_ERROR_SYSCALL 54 (sys_setsockopt produces this error). All this means, that the server side stops sending data. I will check how it looks in Wireshark re: packets sent.

However:
Downloading the package via http/1.1 works fine, you can test it by passing the `--no-alpn` flag to curl, like: `curl -v -O --no-alpn https://statics.teams.microsoft.com/production-osx/1.1.00.5851/Teams_osx.dmg`

I will experiment with curl options to try and fix this.

**Comment by apettinen** [comment]
I decided to force curl to use HTTP/1.1 for now, as the HTTP/2 support by Azure blob storage is too unstable. Commit [a541043](https://github.com/autopkg/apettinen-recipes/commit/a541043e9bec95f9ca47315b7d6d8004beadd1fa) fixes this.

**Comment by SeanHansell** [comment]
Working like a charm now. Thank you!

**Comment by SeanHansell** [comment]
Looks good. Thanks!
