### ISSUE TITLE
MSTeams Error during Run Recipe

### ISSUE THREAD

**Issue by master-vodawagner** [autopkg/apettinen-recipes#7]
Getting this error during Run Recipe

/Users/user/Library/AutoPkg/Cache/local.munki.MSTeams/downloads/Teams_osx.dmg failed: ERROR: hdiutil error nx_kernel_mount:1359: : checkpoint search: largest xid 5, best xid 5 @ 1
nx_kernel_mount:1359: : checkpoint search: largest xid 5, best xid 5 @ 1
nx_kernel_mount:1359: : checkpoint search: largest xid 5, best xid 5 @ 1
nx_kernel_mount:1359: : checkpoint search: largest xid 5, best xid 5 @ 1
nx_kernel_mount:1359: : checkpoint search: largest xid 5, best xid 5 @ 1
nx_kernel_mount:1359: : checkpoint search: largest xid 5, best xid 5 @ 1
nx_kernel_mount:1359: : checkpoint search: largest xid 5, best xid 5 @ 1
nx_kernel_mount:1359: : checkpoint search: largest xid 5, best xid 5 @ 1
with image /Users/user/Library/AutoPkg/Cache/local.munki.MSTeams/downloads/Teams_osx.dmg.
Could not mount /Users/user/Library/AutoPkg/Cache/local.munki.MSTeams/downloads/Teams_osx.dmg!

Any ideas?

**Comment by apettinen** [comment]
This is not actually an error in autopkg recipes, but due to Microsoft shipping an APFS-formatted dmg and subsequently Munki not being able to import the said dmg due to an APFS dmg import bug in munkiimport.

Unless Microsoft reverts back to using HFS+ dmg, the solution is to use a newer version of Munki (Release Candidate) https://munkibuilds.org/3.2.1.3501/ (or newer), where this bug is fixed.

**Comment by apettinen** [comment]
I will close this as Microsoft switched to using pkg instead of dmg.
